_target_: src.models.ml_module.MLLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
  threshold: 1e-4
  threshold_mode: rel
  cooldown: 0
  min_lr: 1e-7
  eps: 1e-8
  verbose: true

net:
  _target_: src.models.components.multimodal_model.MultimodalModel
  num_classes: 18
  hidden_size: 64
  text_pretrained: bert-base-uncased
  img_pretrained: resnet34
  img_weights: DEFAULT

criterion:
  _target_: src.models.components.asymmetric_loss.AsymmetricLossOptimized
  gamma_neg: 4
  gamma_pos: 1
  clip: 0.05
  disable_torch_grad_focal_loss: true

threshold: 0.5

# compile model for faster training with pytorch 2.0
compile: false
